# Generated by Django 4.2 on 2023-04-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pendulum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l1', models.FloatField(default=150)),
                ('l2', models.FloatField(default=120)),
                ('theta1', models.FloatField(default=1.5707963267948966)),
                ('theta2', models.FloatField(default=1.5707963267948966)),
                ('m1', models.FloatField(default=0.1)),
                ('m2', models.FloatField(default=0.1)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
    ]
