# Generated by Django 4.2 on 2023-04-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppendulum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendulum',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
