# Generated by Django 4.2 on 2023-04-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppendulum', '0002_alter_pendulum_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis_l', models.CharField(max_length=100)),
                ('axis_b', models.CharField(max_length=100)),
            ],
        ),
    ]
